"use client";
import "../globals.css";
import Head from "next/head.js";
import { RecoilRoot } from "recoil";
import { ChakraProvider } from "@chakra-ui/react";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="页面描述" />
        <title>淡江大學河川保育創新服務學習課程</title>
      </head>
      <body>
        <div className="flex flex-col h-screen text-white justify-center items-center bg-primary_500">
          {/* <ChakraProvider> */}
          {/* <ThemeProvider> */}
          <RecoilRoot>{children}</RecoilRoot>
          {/* </ThemeProvider> */}
          {/* </ChakraProvider> */}
        </div>
      </body>
    </html>
  );
}
