export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 0;
export const fetchCache = "force-no-store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>水哥的康凡3.0</title>
      </head>
      <body>{children}456</body>
    </html>
  );
}
